### ISSUE TITLE
Add home page for the webapp

### ISSUE THREAD

**Issue by extinctsion** [thekaranpargaie/JobGenie.Api#4]
Need to add homepage in the UI

**Comment by extinctsion** [comment]
Added landing page to the UI

**Comment by thekaranpargaie** [comment]
@extinctsion when you will fix all the design related things there...please mark this as closed!

**Comment by extinctsion** [comment]
@thekaranpargaie we can made he landing page and completed all the task related to landing page, hence im closing this issue.
